### PR TITLE
Vectorization of text and removal of linked images

### PR DESCRIPTION
**Pull request by tanahy**
As recommended by @fortepc I have done some changes to avoid some bugs on the vector files. Please check they render correctly on your system now.

### CODE REVIEW

**Comment by marcoceppi** [comment]
Thanks for these submissions. Two things.

1. Can you please sign the CLA for this repo - this will help to make sure these assets remain CC-BY-SA-NC

2. There seems to be conflicts between the existing repo and what you've provided. Likely this is because you've continued using the same branch as your previous pull request. If that's the case I can take care of resolving the conflicts on merge; or you can rebase this on top of master and resolve the conflicts locally.

**Comment by tanahy** [comment]
Understood, I though I signed the CLA last time, sorry about that.
I don't use git often so please let me check how to rebase locally so that I don't mess it up and I'll come back with a new pull request then.

**Comment by marcoceppi** [comment]
You likely did sign it, however we've made a few formatting updates which results in needing a re-sign.

As for the rebase, it's not a common operation, esp since there are conflicts in file. What I can suggestion:

```
git remote add upstream https://github.com/SilphRoad/silph-league.git
git checkout master
git fetch upstream
git merge --ff-only upstream/master
git checkout vector
# Normally this is just `git rebase master`
# However, there are merge conflicts and we want to use your latest changes.
git rebase -X theirs master
git push -f origin vector
```

**Comment by tanahy** [comment]
Alright, had to change a few things since the fast forward merge didn't work but adding a dummy commit to my old master branch solved it (I don't know what I modified there, actually).

**Comment by marcoceppi** [comment]
Super weird that you weren't able to `--ff-only` that usually is indicative of a problem in your master. I'm going to merge this now; but for future badges I'd recommend this workflow:

```
git checkout master
git fetch upstream
git merge --ff-only upstream/master
git checkout -b name-of-branch
# work, commit, push
```

That way you're always working off of the latest changes from the silph-league repo and each addition/fix is contained to it's own branch.

**Comment by alexvitti** [comment]
@tanah Hey! So I hear you are the one made the Community Day badges? Firstly, awesome job—I really dig them!

That said, I was hoping to laser-etch the March badge onto things like pint glasses etc for prizes and whatnot. However the laser etcher requires rather detailed specs. For me to perform the requisite manipulation of the files they would need to be fully vector. The previous two Community Day files have fully vectorized SVG files on the Silph League assets page, but the SVG I got ahold of for March's has the venusaur art embedded as a flattened image... Would you by chance have an original vector file that you could send me? If so, it would be greatly appreciated! 

Just to super clear, see the attached image :)

march_badge_issue_v01

**Comment by marcoceppi** [comment]
So, just to clarify, @tanah has been helping convert our bitmaps to svg. He mentioned this one being more complext than the last two which is why it's embedded. I'll leave it up to him or anyone else who would like to help vectorize this one!

**Comment by tanahy** [comment]
I'm glad you like them @alexvitti ! As explained by @marcoceppi I'm just vectorizing the designs, not  making them myself. I've being vectorizing the sprites pixel by pixel since they were easy enough up until now. I can't promise you I'll have enough free time to vectorize Venusaur for the March badge, but I'll see what I can do. I might simplify it a bit in other to do it quickly.

**Comment by alexvitti** [comment]
Ahhh, I follow now! Thanks for the responses @tanah and @marcoceppi (and sorry for the delay in getting back to you). Indeed, this design is way more complex from a pixel-count perspective. So yeah, vectorizing it pixel-by-pixel would no doubt have been an _enormous_ pain... Hah, I think you made the smart decision to not do so! I'll just use similar but simpler venusaur vector art to drop within the hex badge template 👍Thanks though!

Also, for whatever it's worth, I spend a lot of time in Illustrator and Photoshop for work / passion projects on the side. While I have minimal skills as a developer, if you ever want help on the more artsy side of things (ideating badge creative, art construction, file building/prepping/converting, etc.) by all means please reach out! I'd be happy to help.

**Comment by alexvitti** [comment]
In case you happened to want it, I made a simplified vector version of the March badge:

[march_badge_BW_vector_v01.eps.zip](https://github.com/SilphRoad/silph-league/files/1843861/march_badge_BW_vector_v01.eps.zip)

**Comment by marcoceppi** [comment]
@alexvitti This is super dope. Can you create a pull request and add this to the repo?

**Pull request merged**
